Repository CommerceWeavers/SyliusSaferpayPlugin, pull requests merged in 2023-10, with the labels that each got.

#90 Fix composer.json to allow Sylius 1.12 after composer updater
  composer.json
  symfony.lock
Labels: Bug

#94 README improvements
  README.md
  docs/configuration.md
  docs/development.md
  docs/img/cw.png
  docs/img/overview/edit-form.png
  docs/img/overview/logs.png
  docs/img/overview/panel.png
  docs/img/overview/payment-logos.png
  docs/img/overview/payment-methods-configuration.png
  docs/img/overview/payment-methods.png
  docs/img/overview/payments-checkout.png
  docs/img/sylius.png
  docs/img/worldline.png
  docs/requirements.md
  symfony.lock
Labels: Documentation, Enhancement

#95 [Documentation] Remove link to unexistent page + minor README improvement
  README.md
  docs/installation.md
Labels: Documentation

#96 Handle non-JSON error response
  spec/Client/SaferpayClientSpec.php
  src/Client/SaferpayClient.php
  src/Client/ValueObject/ErrorResponse.php
Labels: Bug

#97 Improve Saferpay menu
  src/TransactionLog/Menu/AdminMenuListener.php
  translations/messages.en.yaml
Labels: Enhancement

#104 Update README.md
  README.md
Labels: Documentation, Enhancement

#103 Revert "[Maintenance] Use newest test app setup"
  .github/workflows/contract_tests.yaml
Labels: Maintenance
